/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vishu;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vishu tyagi
 */
public class AllCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AllCustomer
     */
    byte[] img;
    public AllCustomer() {
        initComponents();
       setTableOnly();
    }

    
    public Connection getConnection()
    {
    Connection con = null;
    
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/gym","root","");
            
            return con;
        } catch (SQLException ex) {
          
           
            return null;
        }
    
    }
    
    
    public void setTableOnly()
    {
     Connection con = getConnection();
    String query = " SELECT * FROM addcustomer";
    
    Statement st;
    ResultSet rs;
     table.setDefaultRenderer(Object.class, new TableImage());
     DefaultTableModel model = (DefaultTableModel)table.getModel();
        model.setRowCount(0);     
    try {
    st=con.createStatement();
    rs = st.executeQuery(query);
    details1 p;
    
    while(rs.next())   
    {
          Object[] row = new Object[10];
            
                row[0] = rs.getInt("customerid");
            
                      img= rs.getBytes("image");   
                      
                     ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(100,100,Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                   

                row[1] = new JLabel(newImage);
                row[2] = rs.getString("customername");
                // System.out.println(row[2]);
               row[3] = rs.getString("phone");
                row[4] = rs.getString("dateofjoining");
                row[5] = rs.getString("emailid");
                 row[6] = rs.getString("address");       
                row[7] = rs.getString("gender");
                row[8] = rs.getString("package");
                row[9] = rs.getString("amount");
                
                model.addRow(row);    
   
   // p = new details1(rs.getInt("customerid"), img ,rs.getString("customername"),rs.getString("phone"),rs.getString("dateofjoining"),rs.getString("emailid") ,rs.getString("address"),rs.getString("gender"),rs.getString("package"),rs.getString("amount"));
   // productList.add(p);
    
    }  }catch (SQLException ex) {
              // Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
              System.out.println(ex);
           }
    
    
    }
    
 
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  All Customer");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Image", "Name", "phone no", "Joining Date", "Email ID", "Address", "Gender", "Package", "Amount"
            }
        ));
        table.setRowHeight(100);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
