/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vishu;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vishu tyagi
 */
public class CustomerupdateDetail extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    String ImgPath=null;
    String gender= null;
    public CustomerupdateDetail() {
        initComponents();
        GenderPanel.setVisible(true);
        MalePanel.setVisible(false);
        FemalePanel.setVisible(false);
        
    }

       public java.sql.Connection getConnection()
    {
    java.sql.Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/gym","root","");
             //JOptionPane.showMessageDialog(null,"connected");
            return con;
        } catch (SQLException ex) {
            //Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"not connected");
            return null;
        }
    }
       
        
       public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage  = null;
        
        if(imagePath != null)
        {
        myImage  = new ImageIcon(imagePath);
        } else {
        myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(imagepic.getWidth(),imagepic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        dateofJoining = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        amount = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        emailid = new javax.swing.JTextField();
        imagepic = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GenderPanel = new javax.swing.JPanel();
        MalePanel = new javax.swing.JPanel();
        onemonthboys = new javax.swing.JCheckBox();
        threemonthboys = new javax.swing.JCheckBox();
        sixmonthboys = new javax.swing.JCheckBox();
        oneyearboys = new javax.swing.JCheckBox();
        withTrainer = new javax.swing.JCheckBox();
        FemalePanel = new javax.swing.JPanel();
        onemonthgirl = new javax.swing.JCheckBox();
        threemonthgirl = new javax.swing.JCheckBox();
        sixmonthgirl = new javax.swing.JCheckBox();
        oneyeargirl = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        serachname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Choose image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  Change Customer Info");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone No :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date Of Joining :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Email ID :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Amount :");

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        phoneno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });

        dateofJoining.setDateFormatString("dd-MM-yyyy");
        dateofJoining.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        amount.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioMale.setText("Male");
        radioMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioMaleMouseClicked(evt);
            }
        });
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioFemale.setText("Female");
        radioFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioFemaleMouseClicked(evt);
            }
        });
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });

        emailid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });

        imagepic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("package :");

        GenderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenderPanel.setLayout(new java.awt.CardLayout());

        buttonGroup2.add(onemonthboys);
        onemonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onemonthboys.setText("1 Month");
        onemonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onemonthboysMouseClicked(evt);
            }
        });

        buttonGroup2.add(threemonthboys);
        threemonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        threemonthboys.setText("3 Month");
        threemonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threemonthboysMouseClicked(evt);
            }
        });
        threemonthboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threemonthboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(sixmonthboys);
        sixmonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sixmonthboys.setText("6 Month");
        sixmonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixmonthboysMouseClicked(evt);
            }
        });
        sixmonthboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixmonthboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(oneyearboys);
        oneyearboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oneyearboys.setText("1 Year");
        oneyearboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneyearboysMouseClicked(evt);
            }
        });
        oneyearboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneyearboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(withTrainer);
        withTrainer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        withTrainer.setText("With Tranier");
        withTrainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withTrainerMouseClicked(evt);
            }
        });
        withTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withTrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MalePanelLayout = new javax.swing.GroupLayout(MalePanel);
        MalePanel.setLayout(MalePanelLayout);
        MalePanelLayout.setHorizontalGroup(
            MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withTrainer)
                    .addComponent(oneyearboys)
                    .addGroup(MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(threemonthboys)
                        .addComponent(onemonthboys)
                        .addComponent(sixmonthboys)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        MalePanelLayout.setVerticalGroup(
            MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MalePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(onemonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threemonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixmonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneyearboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withTrainer)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        GenderPanel.add(MalePanel, "card2");

        buttonGroup3.add(onemonthgirl);
        onemonthgirl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        onemonthgirl.setText("1 Month");
        onemonthgirl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onemonthgirlMouseClicked(evt);
            }
        });

        buttonGroup3.add(threemonthgirl);
        threemonthgirl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        threemonthgirl.setText("3 Month");
        threemonthgirl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threemonthgirlMouseClicked(evt);
            }
        });
        threemonthgirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threemonthgirlActionPerformed(evt);
            }
        });

        buttonGroup3.add(sixmonthgirl);
        sixmonthgirl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sixmonthgirl.setText("6 Month");
        sixmonthgirl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixmonthgirlMouseClicked(evt);
            }
        });
        sixmonthgirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixmonthgirlActionPerformed(evt);
            }
        });

        buttonGroup3.add(oneyeargirl);
        oneyeargirl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        oneyeargirl.setText("1 Year");
        oneyeargirl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneyeargirlMouseClicked(evt);
            }
        });
        oneyeargirl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneyeargirlActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("With Personal Traning");

        javax.swing.GroupLayout FemalePanelLayout = new javax.swing.GroupLayout(FemalePanel);
        FemalePanel.setLayout(FemalePanelLayout);
        FemalePanelLayout.setHorizontalGroup(
            FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FemalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(oneyeargirl)
                    .addComponent(sixmonthgirl)
                    .addComponent(threemonthgirl)
                    .addComponent(onemonthgirl))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        FemalePanelLayout.setVerticalGroup(
            FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FemalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(onemonthgirl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threemonthgirl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixmonthgirl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneyeargirl)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        GenderPanel.add(FemalePanel, "card3");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Search name :");

        serachname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serachname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachnameActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serachname, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(serachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Clean");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(dateofJoining, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(imagepic, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(radioFemale)))))
                .addGap(52, 52, 52)
                .addComponent(jLabel10)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1))
                    .addComponent(GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateofJoining, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imagepic, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMale)
                            .addComponent(radioFemale))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        // TODO add your handling code here:
        MalePanel.setVisible(false);
               FemalePanel.setVisible(true);
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void withTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withTrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withTrainerActionPerformed

    private void threemonthboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threemonthboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threemonthboysActionPerformed

    private void sixmonthboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixmonthboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixmonthboysActionPerformed

    private void oneyeargirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneyeargirlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneyeargirlActionPerformed

    private void radioMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioMaleMouseClicked
        // TODO add your handling code here:
         if(radioMale.isSelected())
            {
               MalePanel.setVisible(true);
               FemalePanel.setVisible(false);
            }
    }//GEN-LAST:event_radioMaleMouseClicked

    private void radioFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFemaleMouseClicked
        // TODO add your handling code here:
        if(radioFemale.isSelected())
            {
               MalePanel.setVisible(false);
               FemalePanel.setVisible(true);
            }
    }//GEN-LAST:event_radioFemaleMouseClicked

    private void oneyearboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneyearboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneyearboysActionPerformed

    private void threemonthgirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threemonthgirlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threemonthgirlActionPerformed

    private void sixmonthgirlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixmonthgirlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixmonthgirlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
        File selectedFile = file.getSelectedFile();
        String path  = selectedFile.getAbsolutePath();
        imagepic.setIcon(ResizeImage(path,null));
        ImgPath = path;
        }
        else
        {
        System.out.println(" NO FILE Selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void serachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serachnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String name2= serachname.getText();
         
           java.sql.Statement stmt = null;
           java.sql.Connection con = getConnection();    
           
           
                
         try {
           
            stmt = con.createStatement();
     
           String str= "SELECT * FROM addcustomer where customername = '" + name2 + "'";
          ResultSet RS =  stmt.executeQuery(str);
          
              
            if(RS.next())
            {
           
        
                    
                      String name1  = RS.getString("customername");
                      //System.out.println(id1);
                      name.setText(name1);
                      
                      String phonenumber  = RS.getString("phone");
                      //System.out.println(name);
                      phoneno.setText(phonenumber);
                      
            
                      
                         try{
     Date addDate=null;
     addDate = new SimpleDateFormat("dd-MM-yyyy").parse((String)RS.getString("dateofjoining"));
     dateofJoining.setDate(addDate);
     }catch(ParseException ex)
     {
    // Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
     }
             String adress  = RS.getString("address");
                      //System.out.println(name);
                      address.setText(adress);            
                  
               String email  = RS.getString("emailid");
                      //System.out.println(name);
                      emailid.setText(email); 
                      
               String gend  = RS.getString("gender");
                      //System.out.println(name);
                      if(gend.equals("male"))
                      {
                      radioMale.setSelected(true);
                      } else { 
                     radioFemale.setSelected(true);
                         }
                     
                  String pack  = RS.getString("package");
                      //System.out.println(name);
                      if(pack.equals("One Month"))
                      {
                      onemonthboys.setSelected(true);
                      } 
                       if(pack.equals("Three Month"))
                      {
                      threemonthboys.setSelected(true);
                      } 
                       
                         if(pack.equals("Six Month"))
                      {
                      sixmonthboys.setSelected(true);
                      } 
                         
                           if(pack.equals("One Year"))
                      {
                      oneyearboys.setSelected(true);
                      } 
                           
                             if(pack.equals("With Trainer"))
                      {
                      withTrainer.setSelected(true);
                      } 
                             
                               if(pack.equals("1 Month"))
                      {
                      onemonthgirl.setSelected(true);
                      } 
                               
                                 if(pack.equals("3 Month"))
                      {
                      threemonthgirl.setSelected(true);
                      } 


                                 
                       if(pack.equals("6 Month"))
                      {
                      sixmonthgirl.setSelected(true);
                      } 
                                   
                       if(pack.equals("1 Year"))
                      {
                      oneyeargirl.setSelected(true);
                      } 

                      
             String amoun = RS.getString("amount");
                      //System.out.println(name);
                      amount.setText(amoun); 
                      
                     byte[] img = RS.getBytes("image");



                    //Resize The ImageIcon
                    ImageIcon image = new ImageIcon(img);
                    Image im = image.getImage();
                    Image myImg = im.getScaledInstance(imagepic.getWidth(), imagepic.getHeight(),Image.SCALE_SMOOTH);
                    ImageIcon newImage = new ImageIcon(myImg);
                    imagepic.setIcon(newImage);
                
            } else {
            JOptionPane.showMessageDialog(null,"NAME NOT VALID");
            }
            
         }
         catch(Exception ex)
         {
         JOptionPane.showMessageDialog(null,ex.getMessage());
         }
            finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            con.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(con!=null)
            con.close();
      }catch(SQLException se){
         se.printStackTrace();
      }//end finally try
   }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String UpdateQuery = null;
       PreparedStatement ps = null;
       Connection con = getConnection();
       
       // update wihtout image
       if(ImgPath == null)
       {
           try {
               UpdateQuery = "UPDATE addcustomer SET customername = ?, phone = ?, dateofjoining = ?, address = ? ,emailid = ? ,gender = ? ,package = ? ,amount = ? WHERE customername = ?";
               ps =con.prepareStatement(UpdateQuery);
               
               ps.setString(1,name.getText());
               ps.setString(2,phoneno.getText());
               java.util.Date utilDate = dateofJoining.getDate();
               java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
               
                ps.setDate(3,sqlDate);
                
                ps.setString(4,address.getText());
                ps.setString(5,emailid.getText());
                   if(radioMale.isSelected())
            {
                gender="male";
            }
                  else  if(radioFemale.isSelected())
            {
                gender="female";
            }
          
              ps.setString(6,gender);
               String pack=null;
             if(onemonthboys.isSelected())
              {
                pack="One Month";
                amount.setText("600");
              }
              if(threemonthboys.isSelected())
              {
                pack="Three Month";
                amount.setText("1500");
              }
              if(sixmonthboys.isSelected())
              {
                pack="Six Month";
                amount.setText("3000");
              }
              if(oneyearboys.isSelected())
              {
                pack="One Year";
                amount.setText("7000");
              }
              if(withTrainer.isSelected())
              {
                pack="With Trainer";
                amount.setText("2000");
              }
              if(onemonthgirl.isSelected())
              {
                pack="1 Month";
                amount.setText("1000");
              }
               if(threemonthgirl.isSelected())
              {
                pack="3 Month";
                amount.setText("2500");
              }
                if(sixmonthgirl.isSelected())
              {
                pack="6 Month";
                amount.setText("5000");
              }
                if(oneyeargirl.isSelected())
              {
                pack="1 Year";
                amount.setText("10000");
              }
                ps.setString(7,pack);
                 ps.setString(8,amount.getText());
                  ps.setString(9,serachname.getText());
                 ps.executeUpdate();
               //  Show_Products_In_JTable();
                 JOptionPane.showMessageDialog(null,"INFORMTION UPDATED");
                 name.setText(null);
                phoneno.setText(null);
               dateofJoining.setDate(null);
              address.setText(null);
                emailid.setText(null);
                radioMale.setSelected(false);
                 radioFemale.setSelected(false);
         onemonthboys.setSelected(false);
            threemonthboys.setSelected(false);
            sixmonthboys.setSelected(false);
              oneyearboys.setSelected(false);
              withTrainer.setSelected(false);
              onemonthgirl.setSelected(false);
               threemonthgirl.setSelected(false);
              sixmonthgirl.setSelected(false);
              oneyeargirl.setSelected(false);
               amount.setText(null);
                imagepic.setIcon(null);
           } catch (SQLException ex) {
              //Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(null,ex.getMessage());
           }
       }
       
       //update with image
       else{
       try{
           InputStream img = new FileInputStream(new File(ImgPath));
           
           UpdateQuery =  "UPDATE addcustomer SET customername = ?, phone = ?, dateofjoining = ?, address = ? ,emailid = ? ,gender = ? ,package = ? ,amount = ? ,image = ? WHERE customername = ?";
           
           
             ps =con.prepareStatement(UpdateQuery);
                ps.setString(1,name.getText());
               ps.setString(2,phoneno.getText());
               java.util.Date utilDate = dateofJoining.getDate();
               java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
               
                ps.setDate(3,sqlDate);
                
                ps.setString(4,address.getText());
                ps.setString(5,emailid.getText());
                   if(radioMale.isSelected())
            {
                gender="male";
            }
                  else  if(radioFemale.isSelected())
            {
                gender="female";
            }
          
              ps.setString(6,gender);
               String pack=null;
             if(onemonthboys.isSelected())
              {
                pack="One Month";
                amount.setText("600");
              }
              if(threemonthboys.isSelected())
              {
                pack="Three Month";
                amount.setText("1500");
              }
              if(sixmonthboys.isSelected())
              {
                pack="Six Month";
                amount.setText("3000");
              }
              if(oneyearboys.isSelected())
              {
                pack="One Year";
                amount.setText("7000");
              }
              if(withTrainer.isSelected())
              {
                pack="With Trainer";
                amount.setText("2000");
              }
              if(onemonthgirl.isSelected())
              {
                pack="1 Month";
                amount.setText("1000");
              }
               if(threemonthgirl.isSelected())
              {
                pack="3 Month";
                amount.setText("2500");
              }
                if(sixmonthgirl.isSelected())
              {
                pack="6 Month";
                amount.setText("5000");
              }
                if(oneyeargirl.isSelected())
              {
                pack="1 Year";
                amount.setText("10000");
              }
                ps.setString(7,pack);
              ps.setString(8,amount.getText());
                 
               InputStream img1 = new FileInputStream(new File(ImgPath));
                ps.setBlob(9,img1);
                ps.setString(10,serachname.getText());
               
               
                
              
                
            ps.executeUpdate();
            //Show_Products_In_JTable();
           JOptionPane.showMessageDialog(null,"INFORMATION UPDATED");
           
       }catch(Exception ex)
       {
       JOptionPane.showMessageDialog(null,ex.getMessage());
       }
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
         MalePanel.setVisible(true);
               FemalePanel.setVisible(false);
    }//GEN-LAST:event_radioMaleActionPerformed

    private void onemonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onemonthboysMouseClicked
        // TODO add your handling code here:
           if(onemonthboys.isSelected())
              {
               
                amount.setText("600");
              }
    }//GEN-LAST:event_onemonthboysMouseClicked

    private void threemonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threemonthboysMouseClicked
        // TODO add your handling code here:
        if(threemonthboys.isSelected())
              {
                
                amount.setText("1500");
              }
    }//GEN-LAST:event_threemonthboysMouseClicked

    private void sixmonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixmonthboysMouseClicked
        // TODO add your handling code here:
          if(sixmonthboys.isSelected())
              {
               
                amount.setText("3000");
              }
    }//GEN-LAST:event_sixmonthboysMouseClicked

    private void oneyearboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneyearboysMouseClicked
        // TODO add your handling code here:
        if(oneyearboys.isSelected())
              {
               
                amount.setText("7000");
              }
    }//GEN-LAST:event_oneyearboysMouseClicked

    private void withTrainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withTrainerMouseClicked
        // TODO add your handling code here:
         if(withTrainer.isSelected())
              {
              
                amount.setText("2000");
              }
    }//GEN-LAST:event_withTrainerMouseClicked

    private void onemonthgirlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onemonthgirlMouseClicked
        // TODO add your handling code here:
         if(onemonthgirl.isSelected())
              {
                
                amount.setText("1000");
              }
    }//GEN-LAST:event_onemonthgirlMouseClicked

    private void threemonthgirlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threemonthgirlMouseClicked
        // TODO add your handling code here:
          if(threemonthgirl.isSelected())
              {
                
                amount.setText("1000");
              }
    }//GEN-LAST:event_threemonthgirlMouseClicked

    private void sixmonthgirlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixmonthgirlMouseClicked
        // TODO add your handling code here:
        if(threemonthgirl.isSelected())
              {
              
                amount.setText("2500");
              }
    }//GEN-LAST:event_sixmonthgirlMouseClicked

    private void oneyeargirlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneyeargirlMouseClicked
        // TODO add your handling code here:
          if(oneyeargirl.isSelected())
              {
                
                amount.setText("10000");
              }
    }//GEN-LAST:event_oneyeargirlMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         name.setText(null);
                phoneno.setText(null);
                
               
               dateofJoining.setDate(null);
                
                address.setText(null);
                emailid.setText(null);
               
            
                  radioMale.setSelected(false);
                 radioFemale.setSelected(false);
        
                    onemonthboys.setSelected(false);
           
               threemonthboys.setSelected(false);
            
               sixmonthboys.setSelected(false);
              
               oneyearboys.setSelected(false);
              
             
              withTrainer.setSelected(false);
              
              
               onemonthgirl.setSelected(false);
              
              
                threemonthgirl.setSelected(false);
              
              
                 sixmonthgirl.setSelected(false);
              
              
               oneyeargirl.setSelected(false);
              
  
                amount.setText(null);
                
           
                imagepic.setIcon(null);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FemalePanel;
    private javax.swing.JPanel GenderPanel;
    private javax.swing.JPanel MalePanel;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser dateofJoining;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel imagepic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox onemonthboys;
    private javax.swing.JCheckBox onemonthgirl;
    private javax.swing.JCheckBox oneyearboys;
    private javax.swing.JCheckBox oneyeargirl;
    private javax.swing.JTextField phoneno;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField serachname;
    private javax.swing.JCheckBox sixmonthboys;
    private javax.swing.JCheckBox sixmonthgirl;
    private javax.swing.JCheckBox threemonthboys;
    private javax.swing.JCheckBox threemonthgirl;
    private javax.swing.JCheckBox withTrainer;
    // End of variables declaration//GEN-END:variables
}
