/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vishu;


import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;


/**
 *
 * @author vishu tyagi
 */
public class GymFrame extends javax.swing.JFrame {
   GridBagLayout layout = new GridBagLayout();
   Panel p; 
   Panel1 p1;
    Panel2 p2;
    CustomerupdateDetail crd;
    DeleteCustomerDetails dcd;
    AllCustomer al;
    DateReminder dr;
    Aboutus aboutus;
    Contactus contactus;        
   ChangeWallpaper cwall;
    
    public GymFrame() {
      initComponents();
     
     getContentPane().setLayout(layout);
    
        
      
        DynamicPanel.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
     
        cwall=new ChangeWallpaper();
         c.gridx =0;
        c.gridy =0;
        add(cwall,c);
        
        contactus=new Contactus();
         c.gridx =0;
        c.gridy =0;
        add(contactus,c);
        
        aboutus=new Aboutus();
         c.gridx =0;
        c.gridy =0;
        add(aboutus,c);
        
        dr=new DateReminder();
         c.gridx =0;
        c.gridy =0;
        add(dr,c);
        al=new AllCustomer();
         c.gridx =0;
        c.gridy =0;
        add(al,c); 
        dcd=new DeleteCustomerDetails();
        c.gridx =0;
        c.gridy =0;
        add(dcd,c);
        
        crd=new CustomerupdateDetail();
         c.gridx =0;
        c.gridy =0;
        add(crd,c);
        p=new Panel();
        c.gridx =0;
        c.gridy =0;
         add(p,c);
         p1=new Panel1();
        c.gridx =0;
         c.gridy =0;
         add(p1,c);
           p2=new Panel2();
           
         c.gridx =0;
         c.gridy =0;
         add(p2,c);
        DynamicPanel.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
      p.setVisible(false);
      crd.setVisible(false);
      al.setVisible(false);
      dr.setVisible(false);
      aboutus.setVisible(false);
      contactus.setVisible(false);
      cwall.setVisible(false);
      dcd.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        DynamicPanel = new javax.swing.JPanel();
        wallpaper = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        changewall = new javax.swing.JMenuItem();
        Aboutus = new javax.swing.JMenu();
        Contactus = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vishu/dumbbells_fitness_gym_113149_1920x1080.jpg"))); // NOI18N

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DynamicPanelLayout.createSequentialGroup()
                .addComponent(wallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 701, Short.MAX_VALUE)
        );

        jMenu1.setText("Admin");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Add New Admin");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Delete/Change details");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Customer");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem4.setText("Add New Customer");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5.setText("Update Customer Detail");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem6.setText("Delete Custome Detail");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7.setText("All Customer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8.setText("Reminder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Tools");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem9.setText("Calculator");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem10.setText("Notepad");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        changewall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changewall.setText("Change WallPaper");
        changewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changewallActionPerformed(evt);
            }
        });
        jMenu6.add(changewall);

        jMenuBar1.add(jMenu6);

        Aboutus.setText("About us");
        Aboutus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusMouseClicked(evt);
            }
        });
        Aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutusActionPerformed(evt);
            }
        });
        jMenuBar1.add(Aboutus);

        Contactus.setText("Contact us");
        Contactus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Contactus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactusMouseClicked(evt);
            }
        });
        Contactus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactusActionPerformed(evt);
            }
        });
        jMenuBar1.add(Contactus);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         try{
 		        Process p;	//resultText="";
 		        p = Runtime.getRuntime().exec("cmd /c start calc");
 		     
 		        }catch(Exception ae){}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // p1.setVisible(!p1.isVisible());
       p.setVisible(false);
       p1.setVisible(true);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        dcd.setVisible(false);
        dr.setVisible(false);
        crd.setVisible(false);
        al.setVisible(false);
         aboutus.setVisible(false);  
         contactus.setVisible(false);
         cwall.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
p.setVisible(false);
 p1.setVisible(false);
       p2.setVisible(false);
       DynamicPanel.setVisible(true);
       dcd.setVisible(false);
       dr.setVisible(false);
       crd.setVisible(false);
        al.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // p2.setVisible(!p2.isVisible()); 
    p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(true);
         DynamicPanel.setVisible(false);
         dcd.setVisible(false);
         dr.setVisible(false);
         crd.setVisible(false);
        al.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
    // p1.setVisible(!p1.isVisible());
     p.setVisible(false);
    p1.setVisible(true);
        p2.setVisible(false);
       DynamicPanel.setVisible(false);
       dcd.setVisible(false);
       dr.setVisible(false);
       crd.setVisible(false);
        al.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
          p1.setVisible(false);
        p2.setVisible(true);
        DynamicPanel.setVisible(false);
        dcd.setVisible(false);
        dr.setVisible(false);
        p.setVisible(false);
        crd.setVisible(false);
        al.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
      p.setVisible(false);
         p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(true);
        dcd.setVisible(false);
        dr.setVisible(false);
        crd.setVisible(false);
        al.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        crd.setVisible(true);
        p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        dcd.setVisible(false);
        dr.setVisible(false);
        aboutus.setVisible(false);
        al.setVisible(false);
         contactus.setVisible(false);
         cwall.setVisible(false);
         al.setTableOnly();
         dr.setTableOnly();
         dcd.setTableOnly();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try{
 		        Process p;	//resultText="";
 		        p = Runtime.getRuntime().exec("cmd /c start notepad");
 		       // System.out.println("inside");
 		        }catch(Exception ae){}
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        p.setVisible(true);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
         dcd.setVisible(false);
         dr.setVisible(false);
           aboutus.setVisible(false);
        al.setVisible(false);
         contactus.setVisible(false);
         cwall.setVisible(false);
         al.setTableOnly();
         dr.setTableOnly();
         dcd.setTableOnly();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        dcd.setVisible(true);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
        dr.setVisible(false);
         aboutus.setVisible(false);
        al.setVisible(false);
         contactus.setVisible(false);
         cwall.setVisible(false);
         dcd. setTableOnly();
         al.setTableOnly();
         dr.setTableOnly();
         dcd.setTableOnly();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        al.setVisible(true);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
        dr.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
           al.setTableOnly();
          // al.visualize_table(table);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        dr.setVisible(true);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
          aboutus.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void AboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutusActionPerformed
        // TODO add your handling code here:
          aboutus.setVisible(true);
           dr.setVisible(false);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
           contactus.setVisible(false);
           cwall.setVisible(false);
    }//GEN-LAST:event_AboutusActionPerformed

    private void ContactusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactusActionPerformed
      
         contactus.setVisible(true);
         aboutus.setVisible(false);
           dr.setVisible(false);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
         cwall.setVisible(false);
         
    }//GEN-LAST:event_ContactusActionPerformed

    private void AboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMouseClicked
        // TODO add your handling code here:
          contactus.setVisible(false);
         aboutus.setVisible(true);
           dr.setVisible(false);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
        cwall.setVisible(false);
    }//GEN-LAST:event_AboutusMouseClicked

    private void ContactusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactusMouseClicked
        // TODO add your handling code here:
          contactus.setVisible(true);
         aboutus.setVisible(false);
           dr.setVisible(false);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
        cwall.setVisible(false);
    }//GEN-LAST:event_ContactusMouseClicked

    private void changewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changewallActionPerformed
        // TODO add your handling code here:
        cwall.setVisible(true);
         contactus.setVisible(false);
         aboutus.setVisible(false);
           dr.setVisible(false);
          al.setVisible(false);
        dcd.setVisible(false);
          p.setVisible(false);
        p1.setVisible(false);
       p2.setVisible(false);
        DynamicPanel.setVisible(false);
        crd.setVisible(false);
    }//GEN-LAST:event_changewallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GymFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GymFrame().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aboutus;
    private javax.swing.JMenu Contactus;
    public static javax.swing.JPanel DynamicPanel;
    private javax.swing.JMenuItem changewall;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
