/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vishu;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vishu tyagi
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    AllCustomer al;
   // DateReminder dr;
    String ImgPath=null;
     String gender= null;
    public Panel() {
        initComponents();
        GenderPanel.setVisible(true);
        MalePanel.setVisible(false);
        FemalePanel.setVisible(false);
        
    }

     public java.sql.Connection getConnection()
    {
    java.sql.Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/gym","root","");
             //JOptionPane.showMessageDialog(null,"connected");
            return con;
        } catch (SQLException ex) {
          // Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
           // JOptionPane.showMessageDialog(null,"not connected");
            return null;
        }
    }
     
     
       public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage  = null;
        
        if(imagePath != null)
        {
        myImage  = new ImageIcon(imagePath);
        } else {
        myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(image.getWidth(),image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        dateofjoining = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        amount = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        emailid = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GenderPanel = new javax.swing.JPanel();
        MalePanel = new javax.swing.JPanel();
        onemonthboys = new javax.swing.JCheckBox();
        threemonthboys = new javax.swing.JCheckBox();
        sixmonthboys = new javax.swing.JCheckBox();
        oneyearboys = new javax.swing.JCheckBox();
        withtrainer = new javax.swing.JCheckBox();
        FemalePanel = new javax.swing.JPanel();
        onemonthgirls = new javax.swing.JCheckBox();
        threemonthgirls = new javax.swing.JCheckBox();
        sixmonthgirls = new javax.swing.JCheckBox();
        oneyeargirls = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Choose image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  Add New Customer");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Phone No :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date Of Joining :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Email ID :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Amount :");

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        phoneno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });

        dateofjoining.setDateFormatString("dd-MM-yyyy");
        dateofjoining.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        amount.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMale);
        radioMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioMale.setText("Male");
        radioMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioMaleMouseClicked(evt);
            }
        });
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioFemale.setText("Female");
        radioFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioFemaleMouseClicked(evt);
            }
        });
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });

        emailid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });

        image.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("package :");

        GenderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenderPanel.setLayout(new java.awt.CardLayout());

        buttonGroup2.add(onemonthboys);
        onemonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onemonthboys.setText("1 Month");
        onemonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onemonthboysMouseClicked(evt);
            }
        });

        buttonGroup2.add(threemonthboys);
        threemonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        threemonthboys.setText("3 Month");
        threemonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threemonthboysMouseClicked(evt);
            }
        });
        threemonthboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threemonthboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(sixmonthboys);
        sixmonthboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sixmonthboys.setText("6 Month");
        sixmonthboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixmonthboysMouseClicked(evt);
            }
        });
        sixmonthboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixmonthboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(oneyearboys);
        oneyearboys.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oneyearboys.setText("1 Year");
        oneyearboys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneyearboysMouseClicked(evt);
            }
        });
        oneyearboys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneyearboysActionPerformed(evt);
            }
        });

        buttonGroup2.add(withtrainer);
        withtrainer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        withtrainer.setText("With Tranier");
        withtrainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withtrainerMouseClicked(evt);
            }
        });
        withtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withtrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MalePanelLayout = new javax.swing.GroupLayout(MalePanel);
        MalePanel.setLayout(MalePanelLayout);
        MalePanelLayout.setHorizontalGroup(
            MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withtrainer)
                    .addComponent(oneyearboys)
                    .addGroup(MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(threemonthboys)
                        .addComponent(onemonthboys)
                        .addComponent(sixmonthboys)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        MalePanelLayout.setVerticalGroup(
            MalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MalePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(onemonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threemonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixmonthboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneyearboys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withtrainer)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        GenderPanel.add(MalePanel, "card2");

        buttonGroup3.add(onemonthgirls);
        onemonthgirls.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        onemonthgirls.setText("1 Month");
        onemonthgirls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onemonthgirlsMouseClicked(evt);
            }
        });

        buttonGroup3.add(threemonthgirls);
        threemonthgirls.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        threemonthgirls.setText("3 Month");
        threemonthgirls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threemonthgirlsMouseClicked(evt);
            }
        });
        threemonthgirls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threemonthgirlsActionPerformed(evt);
            }
        });

        buttonGroup3.add(sixmonthgirls);
        sixmonthgirls.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sixmonthgirls.setText("6 Month");
        sixmonthgirls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixmonthgirlsMouseClicked(evt);
            }
        });
        sixmonthgirls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixmonthgirlsActionPerformed(evt);
            }
        });

        buttonGroup3.add(oneyeargirls);
        oneyeargirls.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        oneyeargirls.setText("1 Year");
        oneyeargirls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneyeargirlsMouseClicked(evt);
            }
        });
        oneyeargirls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneyeargirlsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("With Personal Traning");

        javax.swing.GroupLayout FemalePanelLayout = new javax.swing.GroupLayout(FemalePanel);
        FemalePanel.setLayout(FemalePanelLayout);
        FemalePanelLayout.setHorizontalGroup(
            FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FemalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(oneyeargirls)
                    .addComponent(sixmonthgirls)
                    .addComponent(threemonthgirls)
                    .addComponent(onemonthgirls))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        FemalePanelLayout.setVerticalGroup(
            FemalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FemalePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(onemonthgirls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threemonthgirls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixmonthgirls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oneyeargirls)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        GenderPanel.add(FemalePanel, "card3");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CLEAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateofjoining, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(153, 153, 153)))
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel7)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(radioFemale))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(dateofjoining, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioMale)
                            .addComponent(radioFemale))
                        .addGap(20, 20, 20)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10))
                    .addComponent(GenderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemaleActionPerformed
        // TODO add your handling code here:
       
               MalePanel.setVisible(false);
               FemalePanel.setVisible(true);
            
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void withtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withtrainerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withtrainerActionPerformed

    private void threemonthboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threemonthboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threemonthboysActionPerformed

    private void sixmonthboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixmonthboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixmonthboysActionPerformed

    private void oneyeargirlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneyeargirlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneyeargirlsActionPerformed

    private void radioMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioMaleMouseClicked
        // 
    }//GEN-LAST:event_radioMaleMouseClicked

    private void radioFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioFemaleMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_radioFemaleMouseClicked

    private void oneyearboysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneyearboysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneyearboysActionPerformed

    private void threemonthgirlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threemonthgirlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threemonthgirlsActionPerformed

    private void sixmonthgirlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixmonthgirlsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixmonthgirlsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
        File selectedFile = file.getSelectedFile();
        String path  = selectedFile.getAbsolutePath();
        image.setIcon(ResizeImage(path,null));
        ImgPath = path;
        }
        else
        {
        System.out.println(" NO FILE Selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           name.setText(null);
                phoneno.setText(null);
                
               //SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
               //java
               dateofjoining.setDate(null);
                
                address.setText(null);
                emailid.setText(null);
                 if(radioMale.isSelected())
            {
                  radioMale.setSelected(false);
              
                
            }
                  else  if(radioFemale.isSelected())
            {
                 radioFemale.setSelected(false);
               
            }
          
              
             if(onemonthboys.isSelected())
              {
                  onemonthboys.setSelected(false);
              }
              if(threemonthboys.isSelected())
              {
               threemonthboys.setSelected(false);
              }
              if(sixmonthboys.isSelected())
              {
               sixmonthboys.setSelected(false);
              }
              if(oneyearboys.isSelected())
              {
               oneyearboys.setSelected(false);
              }
              if(withtrainer.isSelected())
              {
                withtrainer.setSelected(false);
              }
              if(onemonthgirls.isSelected())
              {
               onemonthgirls.setSelected(false);
              }
               if(threemonthgirls.isSelected())
              {
                 threemonthgirls.setSelected(false);
              }
                if(sixmonthgirls.isSelected())
              {
                 sixmonthgirls.setSelected(false);
              }
                if(oneyeargirls.isSelected())
              {
               oneyeargirls.setSelected(false);
              }
              
 
               
                amount.setText(null);
                
                //InputStream img = new FileInputStream(new File(ImgPath));
                image.setIcon(null);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO addcustomer(customername,phone,dateofjoining,address,emailid,gender,package,amount,image) " + " value(?,?,?,?,?,?,?,?,?)");
                String name1 = name.getText();
                
               // String myString = "hellothisisastring";
                   if(Pattern.matches("[a-zA-Z]+",name1))
                        {
                 
                     ps.setString(1,name1);
                         }
                          else
                              {
                                
                                jLabel2.setText("**only alphabet in name feild");
                                
                              } 
                
                
                
                
                
                ps.setString(2,phoneno.getText());
                
               //SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
               //java
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String addDate = dateFormat.format(dateofjoining.getDate());
                ps.setString(3, addDate);
                
                 ps.setString(4,address.getText());
                 ps.setString(5,emailid.getText());
                  if(radioMale.isSelected())
            {
                gender="male";
              
                
            }
                  else  if(radioFemale.isSelected())
            {
                gender="female";
               
            }
          
              ps.setString(6,gender);
              String pack=null;
             if(onemonthboys.isSelected())
              {
                pack="One Month";
                amount.setText("600");
              }
              if(threemonthboys.isSelected())
              {
                pack="Three Month";
                amount.setText("1500");
              }
              if(sixmonthboys.isSelected())
              {
                pack="Six Month";
                amount.setText("3000");
              }
              if(oneyearboys.isSelected())
              {
                pack="One Year";
                amount.setText("7000");
              }
              if(withtrainer.isSelected())
              {
                pack="With Trainer";
                amount.setText("2000");
              }
              if(onemonthgirls.isSelected())
              {
                pack="1 Month";
                amount.setText("1000");
              }
               if(threemonthgirls.isSelected())
              {
                pack="3 Month";
                amount.setText("2500");
              }
                if(sixmonthgirls.isSelected())
              {
                pack="6 Month";
                amount.setText("5000");
              }
                if(oneyeargirls.isSelected())
              {
                pack="1 Year";
                amount.setText("10000");
              }
                ps.setString(7,pack);
                ps.setString(8,amount.getText());
                
                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(9,img);
                ps.executeUpdate();
                  al =  new AllCustomer();
                al.setTableOnly();
                 //  dr =  new DateReminder();
               // dr.setTableOnly();
                //Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null,"Customer information saved");
                
                
                
                
                name.setText(null);
                phoneno.setText(null);
                
               //SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
               //java
               dateofjoining.setDate(null);
                
                address.setText(null);
                emailid.setText(null);
                 if(radioMale.isSelected())
            {
                  radioMale.setSelected(false);
              
                
            }
                  else  if(radioFemale.isSelected())
            {
                 radioFemale.setSelected(false);
               
            }
          
              
             if(onemonthboys.isSelected())
              {
                  onemonthboys.setSelected(false);
              }
              if(threemonthboys.isSelected())
              {
               threemonthboys.setSelected(false);
              }
              if(sixmonthboys.isSelected())
              {
               sixmonthboys.setSelected(false);
              }
              if(oneyearboys.isSelected())
              {
               oneyearboys.setSelected(false);
              }
              if(withtrainer.isSelected())
              {
                withtrainer.setSelected(false);
              }
              if(onemonthgirls.isSelected())
              {
               onemonthgirls.setSelected(false);
              }
               if(threemonthgirls.isSelected())
              {
                 threemonthgirls.setSelected(false);
              }
                if(sixmonthgirls.isSelected())
              {
                 sixmonthgirls.setSelected(false);
              }
                if(oneyeargirls.isSelected())
              {
               oneyeargirls.setSelected(false);
              }
              
 
               
                amount.setText(null);
                
                //InputStream img = new FileInputStream(new File(ImgPath));
                image.setIcon(null);
              
                
            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        
           
            
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void onemonthgirlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onemonthgirlsMouseClicked
        // TODO add your handling code here:
         if(onemonthgirls.isSelected())
              {
                
                amount.setText("1000");
              }
    }//GEN-LAST:event_onemonthgirlsMouseClicked

    private void threemonthgirlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threemonthgirlsMouseClicked
        // TODO add your handling code here:
        if(threemonthgirls.isSelected())
              {
                
                amount.setText("2500");
              }
    }//GEN-LAST:event_threemonthgirlsMouseClicked

    private void sixmonthgirlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixmonthgirlsMouseClicked
        // TODO add your handling code here:
         if(sixmonthgirls.isSelected())
              {
              
                amount.setText("5000");
              }
    }//GEN-LAST:event_sixmonthgirlsMouseClicked

    private void oneyeargirlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneyeargirlsMouseClicked
        // TODO add your handling code here:
           if(oneyeargirls.isSelected())
              {
                
                amount.setText("10000");
              }
    }//GEN-LAST:event_oneyeargirlsMouseClicked

    private void onemonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onemonthboysMouseClicked
        // TODO add your handling code here:
         if(onemonthboys.isSelected())
              {
               
                amount.setText("600");
              }
              
           
              
              
    }//GEN-LAST:event_onemonthboysMouseClicked

    private void threemonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threemonthboysMouseClicked
        // TODO add your handling code here:
        if(threemonthboys.isSelected())
              {
                
                amount.setText("1500");
              }
    }//GEN-LAST:event_threemonthboysMouseClicked

    private void sixmonthboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixmonthboysMouseClicked
        // TODO add your handling code here:
           if(sixmonthboys.isSelected())
              {
               
                amount.setText("3000");
              }
    }//GEN-LAST:event_sixmonthboysMouseClicked

    private void oneyearboysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneyearboysMouseClicked
        // TODO add your handling code here:
        if(oneyearboys.isSelected())
              {
               
                amount.setText("7000");
              }
    }//GEN-LAST:event_oneyearboysMouseClicked

    private void withtrainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withtrainerMouseClicked
        // TODO add your handling code here:
        if(withtrainer.isSelected())
              {
              
                amount.setText("2000");
              }
    }//GEN-LAST:event_withtrainerMouseClicked

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:         if(radioMale.isSelected())
            
              
               MalePanel.setVisible(true);
               FemalePanel.setVisible(false);
                
            
                  
    }//GEN-LAST:event_radioMaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FemalePanel;
    private javax.swing.JPanel GenderPanel;
    private javax.swing.JPanel MalePanel;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField amount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser dateofjoining;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox onemonthboys;
    private javax.swing.JCheckBox onemonthgirls;
    private javax.swing.JCheckBox oneyearboys;
    private javax.swing.JCheckBox oneyeargirls;
    private javax.swing.JTextField phoneno;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JCheckBox sixmonthboys;
    private javax.swing.JCheckBox sixmonthgirls;
    private javax.swing.JCheckBox threemonthboys;
    private javax.swing.JCheckBox threemonthgirls;
    private javax.swing.JCheckBox withtrainer;
    // End of variables declaration//GEN-END:variables
}
